"""add sections table

Revision ID: 8e4798ccdef2
Revises: 086341390bfe
Create Date: 2026-05-29 10:21:06.677394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e4798ccdef2'
down_revision: Union[str, Sequence[str], None] = '086341390bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('navbar', 'hero', 'stats-row', 'data-table', 'form', 'card-grid', 'text-section', 'mobile-header', 'mobile-card-list', 'bottom-nav', name='sectiontype'), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('connecte_a', sa.String(length=200), nullable=True),
    sa.Column('styles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_tracking_id'), 'sections', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_tracking_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
