"""add_nocode_projects_table

Revision ID: ada83e51b4a1
Revises: 7f07c8801c10
Create Date: 2026-08-05 09:13:27.873453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ada83e51b4a1'
down_revision: Union[str, Sequence[str], None] = '7f07c8801c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_conversations_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_conversations_tracking_id CASCADE;')
    op.drop_table('conversations')
    op.execute('DROP INDEX IF EXISTS ix_executions_workflow_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_executions_workflow_tracking_id CASCADE;')
    op.drop_table('executions_workflow')
    op.execute('DROP INDEX IF EXISTS ix_users_email CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_users_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_users_tracking_id CASCADE;')
    op.drop_table('users')
    op.execute('DROP INDEX IF EXISTS ix_donnees_projets_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_donnees_projets_project_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_donnees_projets_tracking_id CASCADE;')
    op.drop_table('donnees_projets')
    op.execute('DROP INDEX IF EXISTS ix_composants_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_composants_tracking_id CASCADE;')
    op.drop_table('composants')
    op.execute('DROP INDEX IF EXISTS ix_tables_schema_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_tables_schema_tracking_id CASCADE;')
    op.drop_table('tables_schema')
    op.execute('DROP INDEX IF EXISTS ix_workflows_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_workflows_tracking_id CASCADE;')
    op.drop_table('workflows')
    op.execute('DROP INDEX IF EXISTS ix_messages_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_messages_tracking_id CASCADE;')
    op.drop_table('messages')
    op.execute('DROP INDEX IF EXISTS ix_etapes_workflow_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_etapes_workflow_tracking_id CASCADE;')
    op.drop_table('etapes_workflow')
    op.execute('DROP INDEX IF EXISTS ix_deployments_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_deployments_interface_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_deployments_tracking_id CASCADE;')
    op.drop_table('deployments')
    op.execute('DROP INDEX IF EXISTS ix_historique_donnees_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_historique_donnees_tracking_id CASCADE;')
    op.drop_table('historique_donnees')
    op.execute('DROP INDEX IF EXISTS ix_fields_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_fields_tracking_id CASCADE;')
    op.drop_table('fields')
    op.execute('DROP INDEX IF EXISTS ix_schemas_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_schemas_tracking_id CASCADE;')
    op.drop_table('schemas')
    op.execute('DROP INDEX IF EXISTS ix_interfaces_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_interfaces_tracking_id CASCADE;')
    op.drop_table('interfaces')
    op.execute('DROP INDEX IF EXISTS ix_pages_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_pages_tracking_id CASCADE;')
    op.drop_table('pages')
    op.execute('DROP INDEX IF EXISTS ix_generations_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_generations_project_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_generations_tracking_id CASCADE;')
    op.drop_table('generations')
    op.execute('DROP INDEX IF EXISTS ix_sections_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_sections_tracking_id CASCADE;')
    op.drop_table('sections')
    op.execute('DROP INDEX IF EXISTS ix_relations_id CASCADE;')
    op.execute('DROP INDEX IF EXISTS ix_relations_tracking_id CASCADE;')
    op.drop_table('relations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('schema_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('ONE_TO_MANY', 'MANY_TO_ONE', 'MANY_TO_MANY', name='relationtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.tracking_id'], name=op.f('relations_schema_id_fkey')),
    sa.ForeignKeyConstraint(['source_table_id'], ['tables_schema.tracking_id'], name=op.f('relations_source_table_id_fkey')),
    sa.ForeignKeyConstraint(['target_table_id'], ['tables_schema.tracking_id'], name=op.f('relations_target_table_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('relations_pkey'))
    )
    op.create_index(op.f('ix_relations_tracking_id'), 'relations', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_relations_id'), 'relations', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('navbar', 'hero', 'stats-row', 'data-table', 'form', 'card-grid', 'text-section', 'mobile-header', 'mobile-card-list', 'bottom-nav', name='sectiontype'), autoincrement=False, nullable=False),
    sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('connecte_a', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('styles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.tracking_id'], name=op.f('sections_page_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sections_pkey'))
    )
    op.create_index(op.f('ix_sections_tracking_id'), 'sections', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('statut', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='statutgeneration'), autoincrement=False, nullable=True),
    sa.Column('url_zip', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('erreur', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('generations_pkey'))
    )
    op.create_index(op.f('ix_generations_tracking_id'), 'generations', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_generations_project_id'), 'generations', ['project_id'], unique=False)
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('interface_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('chemin', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type_page', postgresql.ENUM('mobile', 'tablet', 'desktop', name='typepage'), server_default=sa.text("'mobile'::typepage"), autoincrement=False, nullable=False),
    sa.Column('est_accueil', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.tracking_id'], name='pages_interface_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_pages_tracking_id'), 'pages', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('interfaces',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('interfaces_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='interfaces_pkey'),
    sa.UniqueConstraint('project_id', name='interfaces_project_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_interfaces_tracking_id'), 'interfaces', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    op.create_table('schemas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('schemas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='schemas_pkey'),
    sa.UniqueConstraint('project_id', name='schemas_project_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_schemas_tracking_id'), 'schemas', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_schemas_id'), 'schemas', ['id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('TEXT', 'NUMBER', 'BOOLEAN', 'DATE', 'DATETIME', 'EMAIL', 'URL', 'JSON_FIELD', name='fieldtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unique', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('indexed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables_schema.tracking_id'], name=op.f('fields_table_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fields_pkey'))
    )
    op.create_index(op.f('ix_fields_tracking_id'), 'fields', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_table('historique_donnees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('donnee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ancien_contenu', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('nouveau_contenu', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('modifie_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['donnee_id'], ['donnees_projets.tracking_id'], name=op.f('historique_donnees_donnee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historique_donnees_pkey'))
    )
    op.create_index(op.f('ix_historique_donnees_tracking_id'), 'historique_donnees', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_historique_donnees_id'), 'historique_donnees', ['id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('interface_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='statutdeployment'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deployments_pkey'))
    )
    op.create_index(op.f('ix_deployments_tracking_id'), 'deployments', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_deployments_interface_id'), 'deployments', ['interface_id'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_table('etapes_workflow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('DECLENCHEUR', 'CONDITION', 'ACTION', name='typeetape'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.tracking_id'], name=op.f('etapes_workflow_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('etapes_workflow_pkey'))
    )
    op.create_index(op.f('ix_etapes_workflow_tracking_id'), 'etapes_workflow', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_etapes_workflow_id'), 'etapes_workflow', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', name='messagerole'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.tracking_id'], name=op.f('messages_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_tracking_id'), 'messages', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='workflows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_workflows_tracking_id'), 'workflows', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('tables_schema',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('schema_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.tracking_id'], name=op.f('tables_schema_schema_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tables_schema_pkey'))
    )
    op.create_index(op.f('ix_tables_schema_tracking_id'), 'tables_schema', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_tables_schema_id'), 'tables_schema', ['id'], unique=False)
    op.create_table('composants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('CONTENEUR', 'TEXTE', 'BOUTON', 'FORMULAIRE', 'CHAMP_INPUT', 'LISTE', 'CARTE', 'IMAGE', 'NAVIGATION', name='typecomposant'), autoincrement=False, nullable=False),
    sa.Column('position_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('largeur', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hauteur', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('styles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('connecte_a', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.tracking_id'], name=op.f('composants_page_id_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['composants.tracking_id'], name=op.f('composants_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('composants_pkey'))
    )
    op.create_index(op.f('ix_composants_tracking_id'), 'composants', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_composants_id'), 'composants', ['id'], unique=False)
    op.create_table('donnees_projets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('donnees_projets_pkey'))
    )
    op.create_index(op.f('ix_donnees_projets_tracking_id'), 'donnees_projets', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_donnees_projets_project_id'), 'donnees_projets', ['project_id'], unique=False)
    op.create_index(op.f('ix_donnees_projets_id'), 'donnees_projets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('birth_place', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('plan', postgresql.ENUM('FREE', 'ENTERPRISE', name='userplan'), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('company_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_tracking_id'), 'users', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('executions_workflow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('statut', postgresql.ENUM('EN_COURS', 'REUSSI', 'ECHEC', name='statutexecution'), autoincrement=False, nullable=True),
    sa.Column('declencheur', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultat', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('erreur', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('durée_secondes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.tracking_id'], name=op.f('executions_workflow_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('executions_workflow_pkey'))
    )
    op.create_index(op.f('ix_executions_workflow_tracking_id'), 'executions_workflow', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions_workflow', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('conversations_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_conversations_tracking_id'), 'conversations', ['tracking_id'], unique=True)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###
