"""create data tables

Revision ID: d7d18fd5efa7
Revises: 7beb347f4f01
Create Date: 2026-03-16 23:17:58.127910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d18fd5efa7'
down_revision: Union[str, Sequence[str], None] = '7beb347f4f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_tracking_id'), 'projects', ['tracking_id'], unique=True)
    op.create_table('donnees_projets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donnees_projets_project_id'), 'donnees_projets', ['project_id'], unique=False)
    op.create_table('schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_schemas_id'), 'schemas', ['id'], unique=False)
    op.create_index(op.f('ix_schemas_tracking_id'), 'schemas', ['tracking_id'], unique=True)
    op.create_table('historique_donnees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donnee_id', sa.UUID(), nullable=False),
    sa.Column('ancien_contenu', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('nouveau_contenu', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('modifie_par', sa.UUID(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donnee_id'], ['donnees_projets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_schema_id'), 'tables_schema', ['id'], unique=False)
    op.create_index(op.f('ix_tables_schema_tracking_id'), 'tables_schema', ['tracking_id'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'DATE', 'DATETIME', 'EMAIL', 'URL', 'JSON_FIELD', name='fieldtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables_schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_index(op.f('ix_fields_tracking_id'), 'fields', ['tracking_id'], unique=True)
    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('source_table_id', sa.Integer(), nullable=False),
    sa.Column('target_table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('ONE_TO_MANY', 'MANY_TO_ONE', 'MANY_TO_MANY', name='relationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=100), nullable=True),
    sa.Column('target_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.ForeignKeyConstraint(['source_table_id'], ['tables_schema.id'], ),
    sa.ForeignKeyConstraint(['target_table_id'], ['tables_schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relations_id'), 'relations', ['id'], unique=False)
    op.create_index(op.f('ix_relations_tracking_id'), 'relations', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relations_tracking_id'), table_name='relations')
    op.drop_index(op.f('ix_relations_id'), table_name='relations')
    op.drop_table('relations')
    op.drop_index(op.f('ix_fields_tracking_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_tables_schema_tracking_id'), table_name='tables_schema')
    op.drop_index(op.f('ix_tables_schema_id'), table_name='tables_schema')
    op.drop_table('tables_schema')
    op.drop_table('historique_donnees')
    op.drop_index(op.f('ix_schemas_tracking_id'), table_name='schemas')
    op.drop_index(op.f('ix_schemas_id'), table_name='schemas')
    op.drop_table('schemas')
    op.drop_index(op.f('ix_donnees_projets_project_id'), table_name='donnees_projets')
    op.drop_table('donnees_projets')
    op.drop_index(op.f('ix_projects_tracking_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
