"""create all tables

Revision ID: f62c603f6dff
Revises: 
Create Date: 2026-05-29 09:15:17.851225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f62c603f6dff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donnees_projets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donnees_projets_id'), 'donnees_projets', ['id'], unique=False)
    op.create_index(op.f('ix_donnees_projets_project_id'), 'donnees_projets', ['project_id'], unique=False)
    op.create_index(op.f('ix_donnees_projets_tracking_id'), 'donnees_projets', ['tracking_id'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_tracking_id'), 'workflows', ['tracking_id'], unique=True)
    op.create_table('etapes_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DECLENCHEUR', 'CONDITION', 'ACTION', name='typeetape'), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etapes_workflow_id'), 'etapes_workflow', ['id'], unique=False)
    op.create_index(op.f('ix_etapes_workflow_tracking_id'), 'etapes_workflow', ['tracking_id'], unique=True)
    op.create_table('executions_workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.Enum('EN_COURS', 'REUSSI', 'ECHEC', name='statutexecution'), nullable=True),
    sa.Column('declencheur', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('resultat', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('erreur', sa.String(length=500), nullable=True),
    sa.Column('durée_secondes', sa.Float(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_workflow_id'), 'executions_workflow', ['id'], unique=False)
    op.create_index(op.f('ix_executions_workflow_tracking_id'), 'executions_workflow', ['tracking_id'], unique=True)
    op.create_table('historique_donnees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=True),
    sa.Column('donnee_id', sa.UUID(), nullable=False),
    sa.Column('ancien_contenu', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('nouveau_contenu', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('modifie_par', sa.UUID(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donnee_id'], ['donnees_projets.tracking_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_donnees_id'), 'historique_donnees', ['id'], unique=False)
    op.create_index(op.f('ix_historique_donnees_tracking_id'), 'historique_donnees', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historique_donnees_tracking_id'), table_name='historique_donnees')
    op.drop_index(op.f('ix_historique_donnees_id'), table_name='historique_donnees')
    op.drop_table('historique_donnees')
    op.drop_index(op.f('ix_executions_workflow_tracking_id'), table_name='executions_workflow')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions_workflow')
    op.drop_table('executions_workflow')
    op.drop_index(op.f('ix_etapes_workflow_tracking_id'), table_name='etapes_workflow')
    op.drop_index(op.f('ix_etapes_workflow_id'), table_name='etapes_workflow')
    op.drop_table('etapes_workflow')
    op.drop_index(op.f('ix_workflows_tracking_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_donnees_projets_tracking_id'), table_name='donnees_projets')
    op.drop_index(op.f('ix_donnees_projets_project_id'), table_name='donnees_projets')
    op.drop_index(op.f('ix_donnees_projets_id'), table_name='donnees_projets')
    op.drop_table('donnees_projets')
    # ### end Alembic commands ###
